# Generated by Django 6.0.3 on 2026-03-30 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0007_alter_productoimagen_activa_and_more'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('cuerpo_mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('total_destinatarios', models.PositiveIntegerField(default=0, verbose_name='Total Destinatarios')),
                ('enviados_exitosos', models.PositiveIntegerField(default=0, verbose_name='Enviados Exitosos')),
                ('enviados_fallidos', models.PositiveIntegerField(default=0, verbose_name='Enviados Fallidos')),
                ('tipo_envio', models.CharField(choices=[('promocion', 'Promoción de Producto'), ('campana', 'Campaña Manual'), ('bienvenida', 'Bienvenida Automática'), ('notificacion', 'Notificación General')], default='campana', max_length=20, verbose_name='Tipo de Envío')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviando', 'Enviando'), ('completado', 'Completado'), ('error', 'Error'), ('parcial', 'Parcial (algunos fallaron)')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_realizados', to='usuario.usuario', verbose_name='Autor')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto', verbose_name='Producto Promocionado')),
            ],
            options={
                'verbose_name': 'Historial de Envío',
                'verbose_name_plural': 'Historiales de Envíos',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='DestinatarioEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del Destinatario')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('rebotado', 'Rebotado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Destinatario')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='correos.historialenvio', verbose_name='Historial de Envío')),
            ],
            options={
                'verbose_name': 'Destinatario de Envío',
                'verbose_name_plural': 'Destinatarios de Envíos',
                'unique_together': {('historial', 'destinatario')},
            },
        ),
    ]
