# Generated by Django 6.0.3 on 2026-03-21 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transportadora',
                'verbose_name_plural': 'transportadoras',
                'db_table': 'transportadoras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField()),
                ('numero_guia', models.CharField(max_length=80, unique=True)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='preparando', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='ventas.venta')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='envios.transportadora')),
            ],
            options={
                'verbose_name': 'envio',
                'verbose_name_plural': 'envios',
                'db_table': 'envios',
                'ordering': ['-fecha_envio', '-id'],
            },
        ),
    ]
