# Generated by Django 6.0.3 on 2026-04-15 00:07

from django.db import migrations, models


def _marcar_correos_existentes_como_verificados(apps, schema_editor):
    Usuario = apps.get_model("usuario", "Usuario")
    Usuario.objects.all().update(correo_verificado=True)


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion_correo',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(_marcar_correos_existentes_como_verificados, migrations.RunPython.noop),
    ]
