# Generated by Django 6.0.3 on 2026-04-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_correo_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_verificado',
            field=models.BooleanField(default=True),
        ),
    ]
