# Generated by Django 6.0.3 on 2026-03-21 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversacion_id', models.CharField(db_index=True, max_length=120)),
                ('tipo_remitente', models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado')], max_length=20)),
                ('leido', models.BooleanField(default=False)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('leido', 'Leido'), ('respondido', 'Respondido')], default='enviado', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('destinatario_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_directos_recibidos', to='usuario.usuario')),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_directos_asignados', to='usuario.usuario')),
                ('mensaje_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_hilo', to='mensajeria.mensajedirecto')),
                ('remitente_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_directos_enviados', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'mensaje directo',
                'verbose_name_plural': 'mensajes directos',
                'db_table': 'mensajes_directos',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_remitente', models.CharField(choices=[('admin', 'Administrador'), ('sistema', 'Sistema'), ('empleado', 'Empleado')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('data_adicional', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_empleado_recibidos', to='usuario.usuario')),
                ('remitente_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_empleado_enviados', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'mensaje a empleado',
                'verbose_name_plural': 'mensajes a empleados',
                'db_table': 'mensajes_empleado',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('icono', models.CharField(max_length=80)),
                ('leida', models.BooleanField(default=False)),
                ('data_adicional', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
    ]
