from django.urls import path

from usuario.adapters.web.session_views import (
    home_portal,
    login_web,
    logout_web,
    registro_web,
)
from web import views

urlpatterns = [
    path("", views.root_entry, name="root"),
    path("inicio/", views.home, name="inicio_autenticado"),
    path(
        "cliente/catalogo/agregar-carrito/",
        views.catalogo_agregar_carrito,
        name="web_catalogo_agregar_carrito",
    ),
    path(
        "cliente/catalogo/toggle-favorito/",
        views.catalogo_toggle_favorito,
        name="web_catalogo_toggle_favorito",
    ),
    path(
        "empleado/",
        views.empleado_dashboard,
        kwargs={"seccion": "inicio"},
        name="web_empleado_inicio",
    ),
    path("empleado/<slug:seccion>/", views.empleado_dashboard, name="web_empleado_seccion"),
    path("admin/perfil/", views.perfil_admin, name="web_admin_perfil"),
    path("admin/usuarios/crear/", views.admin_usuario_crear, name="web_admin_usuario_crear"),
    path(
        "admin/usuarios/<int:usuario_id>/estado/",
        views.admin_usuario_estado,
        name="web_admin_usuario_estado",
    ),
    path("admin/usuarios/", views.admin_usuarios, name="web_admin_usuarios"),
    path("admin/inventario/producto/crear/", views.admin_producto_crear, name="web_admin_producto_crear"),
    path(
        "admin/inventario/producto/<int:producto_id>/estado/",
        views.admin_producto_estado,
        name="web_admin_producto_estado",
    ),
    path(
        "admin/inventario/catalogo/categoria/",
        views.admin_catalogo_categoria_agregar,
        name="web_admin_catalogo_categoria_agregar",
    ),
    path(
        "admin/inventario/catalogo/marca/",
        views.admin_catalogo_marca_agregar,
        name="web_admin_catalogo_marca_agregar",
    ),
    path("admin/inventario/", views.admin_inventario, name="web_admin_inventario"),
    path("admin/proveedores/crear/", views.admin_proveedor_crear, name="web_admin_proveedor_crear"),
    path(
        "admin/proveedores/<int:proveedor_id>/estado/",
        views.admin_proveedor_estado,
        name="web_admin_proveedor_estado",
    ),
    path("admin/proveedores/", views.admin_proveedores, name="web_admin_proveedores"),
    path("admin/pagos/", views.admin_pagos, name="web_admin_pagos"),
    path(
        "admin/pagos/detalle/<int:pago_id>/",
        views.admin_pago_detalle,
        name="web_admin_pago_detalle",
    ),
    path(
        "admin/pagos/factura/<int:pago_id>/",
        views.admin_pago_factura,
        name="web_admin_pago_factura",
    ),
    path(
        "admin/pedidos/<int:venta_id>/",
        views.admin_pedido_detalle,
        name="web_admin_pedido_detalle",
    ),
    path("admin/pedidos/", views.admin_pedidos, name="web_admin_pedidos"),
    path("login/", login_web, name="web_login"),
    path("logout/", logout_web, name="web_logout"),
    path("registro/", registro_web, name="web_registro"),
    path("cuenta/", home_portal, name="home_portal"),
    path("cliente/perfil/editar/", views.perfil_editar, name="web_cliente_perfil_editar"),
    path("cliente/perfil/desactivar/", views.perfil_desactivar, name="web_cliente_perfil_desactivar"),
    path("cliente/perfil/", views.perfil_cliente, name="web_cliente_perfil"),
    path("favoritos/", views.favoritos_page, name="web_favoritos"),
    path("favoritos/quitar/", views.favorito_quitar, name="web_favorito_quitar"),
    path("favoritos/al-carrito/", views.favorito_agregar_carrito, name="web_favorito_al_carrito"),
    path("cliente/notificaciones/", views.notificaciones_cliente, name="web_cliente_notificaciones"),
    path("carrito/actualizar/", views.carrito_actualizar, name="web_carrito_actualizar"),
    path("carrito/eliminar/", views.carrito_eliminar, name="web_carrito_eliminar"),
    path("carrito/vaciar/", views.carrito_vaciar, name="web_carrito_vaciar"),
    path("carrito/", views.carrito_page, name="web_carrito"),
    path(
        "cliente/checkout/informacion/",
        views.checkout_informacion,
        name="web_cliente_checkout_info",
    ),
    path(
        "cliente/checkout/direccion/",
        views.checkout_direccion,
        name="web_cliente_checkout_direccion",
    ),
    path("cliente/checkout/envio/", views.checkout_envio, name="web_cliente_checkout_envio"),
    path("cliente/checkout/pago/", views.checkout_pago, name="web_cliente_checkout_pago"),
    path(
        "cliente/checkout/revision/",
        views.checkout_revision,
        name="web_cliente_checkout_revision",
    ),
    path(
        "cliente/checkout/finalizar/",
        views.checkout_finalizar,
        name="web_cliente_checkout_finalizar",
    ),
    path(
        "cliente/checkout/paypal/iniciar/",
        views.checkout_paypal_iniciar,
        name="web_cliente_checkout_paypal_iniciar",
    ),
    path(
        "cliente/checkout/paypal/retorno/",
        views.checkout_paypal_retorno,
        name="web_cliente_checkout_paypal_retorno",
    ),
    path(
        "cliente/checkout/confirmacion/",
        views.checkout_confirmacion,
        name="web_cliente_checkout_confirmacion",
    ),
    path("cliente/pedidos/", views.pedidos_cliente, name="web_cliente_pedidos"),
    path("cliente/mis-compras/", views.mis_compras, name="web_cliente_mis_compras"),
    path(
        "cliente/mis-compras/<int:venta_id>/factura/",
        views.cliente_factura_compra,
        name="web_cliente_factura_compra",
    ),
    path("cliente/atencion-cliente/", views.atencion_cliente, name="web_cliente_atencion"),
    path("producto/<int:producto_id>/", views.producto_detalle, name="web_producto_detalle"),
]
