# Generated by Django 6.0.3 on 2026-03-21 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_factura', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPagoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=30)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('ultimos_cuatro', models.CharField(blank=True, max_length=4)),
                ('nombre_titular', models.CharField(blank=True, max_length=150)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('mes_expiracion', models.CharField(blank=True, max_length=2)),
                ('anio_expiracion', models.CharField(blank=True, max_length=4)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cuotas', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_usuario', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'metodo de pago de usuario',
                'verbose_name_plural': 'metodos de pago de usuario',
                'db_table': 'metodos_pago_usuario',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('tarjeta_credito', 'Tarjeta de credito'), ('tarjeta_debito', 'Tarjeta de debito'), ('pse', 'PSE'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=30)),
                ('fecha_compra', models.DateTimeField()),
                ('tiempo_entrega', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medios_pago', to='venta.detalleventa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medios_pago', to='usuario.usuario')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medios_pago', to='pago.pago')),
            ],
            options={
                'verbose_name': 'medio de pago',
                'verbose_name_plural': 'medios de pago',
                'db_table': 'medios_pago',
                'ordering': ['-id'],
            },
        ),
    ]
