# Generated by Django 6.0.3 on 2026-03-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediopago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_credito', 'Tarjeta de credito'), ('tarjeta_debito', 'Tarjeta de debito'), ('pse', 'PSE'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=30),
        ),
    ]
