# Generated by Django 6.0.3 on 2026-04-15 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
        ('producto', '0011_alter_producto_imagen_url_max_length'),
        ('proveedor', '0001_initial'),
        ('usuario', '0003_correo_verificado_default_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudOrdenCompraProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_aprobada', models.PositiveIntegerField(blank=True, null=True)),
                ('comentario_empleado', models.TextField(blank=True, default='')),
                ('motivo_rechazo', models.TextField(blank=True, default='')),
                ('marca_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('color_snapshot', models.CharField(blank=True, default='', max_length=40)),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_oc_prov', to='usuario.usuario')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_origen', to='orden.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_oc_prov', to='producto.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_oc_prov', to='proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'solicitud orden compra prov',
                'verbose_name_plural': 'solicitudes órdenes compra prov',
                'db_table': 'solicitudes_oc_prov',
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
