# Generated by Django 6.0.4 on 2026-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_recepcion_orden_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudordencompraprov',
            name='estado',
            field=models.CharField(choices=[('borrador', 'En edición'), ('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20),
        ),
    ]
