# Generated by Django 6.0.3 on 2026-03-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_caracteristica'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
