# Generated by Django 6.0.3 on 2026-03-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCatalogoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('categoria', 'Categoría'), ('marca', 'Marca')], db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'productos_catalogo_extra',
                'constraints': [models.UniqueConstraint(fields=('tipo', 'nombre'), name='uniq_catalogo_extra_tipo_nombre')],
            },
        ),
    ]
