# Generated by Django 6.0.3 on 2026-03-26 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_imagen'),
        ('producto', '0005_producto_catalogo_extra'),
    ]

    operations = [
    ]
