# Generated by Django 6.0.3 on 2026-03-30 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_merge_20260325_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
