# Generated by Django 6.0.3 on 2026-04-04 22:06

from django.db import migrations, models
from django.db.models import F


def backfill_stock_inicial(apps, schema_editor):
    Producto = apps.get_model("producto", "Producto")
    Producto.objects.all().update(stock_inicial=F("stock"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0008_producto_promocion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock_inicial",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Unidades con las que se registró el producto (no se reduce con ventas).",
            ),
        ),
        migrations.RunPython(backfill_stock_inicial, noop_reverse),
    ]
