# Generated by Django 6.0.3 on 2026-04-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_producto_stock_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Inventario disponible: baja con ventas y sube con compras u ajustes.', verbose_name='stock actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_inicial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Fijo desde el alta (Excel o manual). No cambia con ventas ni con edición de ficha.', verbose_name='stock inicial'),
        ),
    ]
