# Generated by Django 6.0.3 on 2026-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_producto_stock_labels_editable_false'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado_en', '-id'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
